name:                brogalik
version:             0.1.0.0
github:              "gerdreiss/brogalik"
license:             BSD3
author:              "Gerd Reiss"
maintainer:          "gerd@reiss.pro"
copyright:           "Gerd Reiss"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gerdreiss/brogalik#readme>

dependencies:
- base >= 4.7 && < 5
- brick
- vty
- array
- containers
- microlens-ghc
- microlens-th
- mtl
- text
- terminal-size

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings
    - TemplateHaskell

executables:
  brogalik-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    - -Wunused-imports
    - -Wwarn=unused-imports
    default-extensions:
      - OverloadedStrings
    dependencies:
    - brogalik

tests:
  brogalik-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brogalik
